# @format

os: linux

language: node_js

node_js:
  - lts/argon
  - lts/boron
  - lts/carbon
  - lts/dubnium

dist: trusty

cache:
  directories:
    - '$HOME/.node_packages'

group: stable

install:
  - npm i -g npm@latest
  - npm i -g typescript@latest @types/node@latest
  - npm i -g ts-jest@latest
  - npm i -g jest@latest @types/jest@latest
  - npm i -g tslint-config-airbnb@latest tslint-config-prettier@latest tslint-react@latest
  - npm i -g tslint@latest
  - npm i -g coveralls@latest
  - npm install

script:
  - npm run build
  - ls -alg

'.result': configured
