language:
  node_js

  # Release  Status           Codename  Initial Release  Active LTS Start  Maintenance LTS Start  End-of-life
  #―0000000―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
  #  v15     Current                    2020-10-20                         2021-04-01             2021-06-01
  #  v14     Active LTS       Fermium   2020-04-21       2020-10-27        2021-10-19             2023-04-30
  #  v12     Active LTS       Erbium    2019-04-23       2019-10-21        2020-11-30             2022-04-30
  #  v10     Maintenance LTS  Dubnium   2018-04-24       2018-10-30        2020-05-19             2021-04-30

node_js:
  - node # latest stable Node.js release
  - lts/* # latest LTS Node.js release
  - 12 # latest 12.x release
  - 10 # latest 10.x release

os:
  - linux

cache:
  directories:
    - "$HOME/.node_packages"

group: stable

branches:
  # blocklist
  except:
    - next/feature
  # safelist
  only:
    - master
    - next/from-v1.2.0-next-20201226

install:
  - npm i -g npm@latest
  - npm i -g typescript@latest @types/node@latest
  - npm i -g ts-jest@latest
  - npm i -g jest@latest @types/jest@latest
  - npm i -g tslint-config-airbnb@latest tslint-config-prettier@latest tslint-react@latest
  - npm i -g tslint@latest
  - npm i -g coveralls@latest
  - npm install

script:
  - yarn run CI
  - ls -alg
  - echo "Running tests against $(node -v)..."

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script:
        - jest --coverage --runInBand --detectOpenHandles --colors && cat ./build/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./build/coverage
        - ls -alksShg

".result": configured

matrix:
  fast_finish: true
  include:
    - node_js: "lts/*"
      env: PRETEST=true
    - node_js: "lts/*"
      env: POSTTEST=true
    - node_js: "10.6"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "10.5"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "10.4"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "10.3"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "10.2"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "10.1"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "10.0"
  allow_failures:
    - os: osx
    - env: TEST=true ALLOW_FAILURE=true
